### PR TITLE
Add ci-related files

### PR DESCRIPTION
**Pull request by jafcrocker**

### CODE REVIEW

**Comment by zingbot-zenoss** [comment]
Can one of the admins verify this patch?

**Comment by zingbot-zenoss** [comment]
Test

**Comment by jafcrocker** [comment]
retest this

**Comment by jafcrocker** [comment]
retest this

**Comment by zingbot-zenoss** [comment]
retest this

**Comment by jafcrocker** [comment]
retest this

**Comment by jafcrocker** [comment]
retest this

**Comment by jafcrocker** [comment]
what?

**Pull request closed without merging**
